### ISSUE TITLE
Qiita API で本文から特定の文字列を取得する方法が知りたい

### ISSUE THREAD

**Issue by himajin315** [yasslab/qiita-team-reporter#1]
Qiita API v2ドキュメント: https://qiita.com/api/v2/docs

**Comment by yasulab** [comment]
んー、この Issue だと、どのタイミングで Close するかがわからないと思います🤔 (Issue は Open -> Close までがセットなので)

**Comment by hanachin** [comment]
「本文」って特定の1記事の本文のことなのかな?
「特定の文字列」ってなんだろう?
もうちょっと具体的に書かれていないと解決できなさそうなので、closeします。

必要であればissue細かくわけてもらえると助かります。
