### ISSUE TITLE
gemとしてpublishする

### ISSUE THREAD

**Issue by hanachin** [yasslab/qiita-team-reporter#8]
このコマンドはqiita gemに依存しています。
gemとしてpublishすると以下のような点でよさそうです

- qiita gemへの依存関係をシェルスクリプトによる確認以外の方法で明示できる
- gem install qiita-team-reporterで依存関係のあるqiita gemが同時にはいる
- gem installでインストールするとパスが通るのでインストールが楽
- gem installで手軽に更新できる

ただしgemとしてpublishしてもjqコマンドへの依存が残ったままなので、依然としてシェルスクリプトによる確認は必要ですね。

もっともjsonの整形もRubyで行うようにすればjqへの依存も取り払えるかもしれません。

**Comment by yasulab** [comment]
.oO(RubyKaigi 2017 周りの情報がナラさんにも見えているはずなので、今ならナラさんも開発に参加できるかもしれないと踏んで、assign してみました ><)

**Comment by hanachin** [comment]
https://rubygems.org/gems/qiita-team-reporter
https://github.com/yasslab/qiita-team-reporter/tree/v0.1.0

```
% gem build qiita-team-reporter
WARNING:  open-ended dependency on qiita (>= 0) is not recommended
  if qiita is semantically versioned, use:
    add_runtime_dependency 'qiita', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: qiita-team-reporter
  Version: 0.1.0
  File: qiita-team-reporter-0.1.0.gem
% gem push qiita-team-reporter-0.1.0.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: qiita-team-reporter (0.1.0)
% gem owner qiita-team-reporter -a yasulab@gmail.com
Owner added successfully.
Owners for gem: qiita-team-reporter
- yasulab@gmail.com
- hanachin@gmail.com
```

**Comment by yasulab** [comment]
🎉

**Comment by hanachin** [comment]
`gem i qiita-team-reporter`で入れて環境変数諸々設定して動きましたー。

assignされた段階で結構書きかけてたので雑にタスクとっちゃいましたすみません 💦
